### PR TITLE
Make GitHub detect *.f as Forth.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello,

Please merge this, if you'd like GitHub to detect your `.f` files as Forth.

Thanks!

### CODE REVIEW

**Comment by pablooliveira** [comment]
Hi @larsbrinkhoff, Thanks for the PR, which seems fine :-)

JonesForth-arm was ported as the final project in an embedded system's lectures I teach at UVSQ. This repository was set up by one of my students, but sadly I forgot to ask him to add me as a maintainer. 

I'm trying to reach him to see if he can add me now as an owner to the repository, so I can merge your PR. Hopefully, I will get back to you soon !

**Comment by larsbrinkhoff** [comment]
Thank you!

**Comment by pablooliveira** [comment]
Merged. Thanks for the PR !

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Pull request merged**
